package com.easy.query.test.mysql8.dto;


import lombok.Data;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;

import java.util.List;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.easy.query.test.mysql8.entity.condition.MyTask }
 *
 * @author xuejiaming
 * @easy-query-dto schema: normal
 */
@Data
public class MyTaskDTO1 {


    private String id;
    private String name;
    /**
     * version1的子任务
     **/
    @Navigate(value = RelationTypeEnum.OneToMany)
    private List<InternalMySubTask1> mySubTask1List;
    /**
     * version2的扩展
     **/
    @Navigate(value = RelationTypeEnum.OneToOne)
    private InternalMyTask2Ext myTask2Ext;


    /**
     * {@link com.easy.query.test.mysql8.entity.condition.MySubTask1 }
     *
     */
    @Data
    public static class InternalMySubTask1 {

        private String id;
        private String name;


    }


    /**
     * {@link com.easy.query.test.mysql8.entity.condition.MyTask2Ext }
     *
     */
    @Data
    public static class InternalMyTask2Ext {

        private String id;
        private String name;


    }

}
